# Generated by Django 5.2.1 on 2025-05-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0005_vehiclemodel_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='cars.vehiclemodel')),
            ],
            options={
                'db_table': 'viewer',
            },
        ),
    ]
