# Generated by Django 5.2.1 on 2025-05-14 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{1,19}$', 'Name must start with a capital letter and be 2–20 characters long')])),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\- ]{1,30}$', 'Only letters, numbers, dashes and spaces are allowed (max 30 characters)')])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.brand')),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2025)])),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], max_length=9)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=8)),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.6), django.core.validators.MaxValueValidator(10.0)])),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('price_input', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], max_length=3)),
                ('is_active', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='cars.carmodel')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
