# Generated by Django 5.2.1 on 2025-05-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='user_profile',
            new_name='user',
        ),
    ]
