# Generated by Django 5.2.1 on 2025-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_user_profile_vehiclemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='edit_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
