# Generated by Django 5.2.1 on 2025-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_vehiclemodel_edit_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='region',
            field=models.CharField(choices=[('vinnytsia', 'Вінницька'), ('volyn', 'Волинська'), ('dnipropetrovsk', 'Дніпропетровська'), ('donetsk', 'Донецька'), ('zhytomyr', 'Житомирська'), ('zakarpattia', 'Закарпатська'), ('zaporizhzhia', 'Запорізька'), ('ivano-frankivsk', 'Івано-Франківська'), ('kyivska', 'Київська'), ('kyiv', 'Київ'), ('kirovohrad', 'Кіровоградська'), ('luhansk', 'Луганська'), ('lviv', 'Львівська'), ('mykolaiv', 'Миколаївська'), ('odesa', 'Одеська'), ('poltava', 'Полтавська'), ('rivne', 'Рівненська'), ('sumy', 'Сумська'), ('ternopil', 'Тернопільська'), ('kharkiv', 'Харківська'), ('kherson', 'Херсонська'), ('khmelnytskyi', 'Хмельницька'), ('cherkasy', 'Черкаська'), ('chernivtsi', 'Чернівецька'), ('chernihiv', 'Чернігівська')], default='VOLYN', max_length=50),
        ),
    ]
