# Generated by Django 5.2.1 on 2025-05-25 16:28

import django.db.models.deletion
from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_vehiclemodel_price_eur_vehiclemodel_price_uah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.services.file_service.upload_vehicle_photo)),
                ('is_main', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_photos', to='cars.vehiclemodel')),
            ],
            options={
                'db_table': 'vehicle_photos',
            },
        ),
    ]
