# Generated by Django 5.2.1 on 2025-05-26 10:01

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_vehiclephotomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclephotomodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_vehicle_photo),
        ),
    ]
