# Generated by Django 5.2 on 2025-08-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_vehiclephotomodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='edit_attempts',
        ),
    ]
