# Generated by Django 5.2.1 on 2025-05-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
