# Generated by Django 5.2 on 2025-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_is_admin_remove_profile_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vehicle_creation_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
